apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 5
  template:
    metadata:
      labels:
        app: goserver
      annotations:
          kubernetes.io/change-cause: "Updated to version 2.0 at $(date)"
    spec:
      containers:
        - name: goserver
          image: gezielcarvalho/hello-go:v7
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"