apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 6
  template:
    metadata:
      labels:
        app: goserver
      annotations:
        kubernetes.io/change-cause: "Upgrade to v11"
    spec:
      containers:
        - name: goserver
          image: gezielcarvalho/hello-go:v11
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"